# Generated by Django 5.2.5 on 2025-09-01 22:16

import localflavor.es.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', localflavor.es.models.ESPostalCodeField(max_length=5)),
                ('province', models.CharField(max_length=90)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('tax_id', localflavor.es.models.ESIdentityCardNumberField(blank=True, max_length=9, null=True)),
                ('production_activity', models.CharField(help_text='Type of farming or production activity', max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['full_name'],
            },
        ),
    ]
