# Generated by Django 5.2.5 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
