# Generated by Django 5.2.5 on 2025-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0002_suppliersmodel_approved_suppliersmodel_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliersmodel',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='suppliersmodel',
            name='reviewed',
        ),
    ]
