# Generated by Django 5.2.5 on 2025-09-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0003_remove_suppliersmodel_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliersmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
