# Generated by Django 5.2.5 on 2025-09-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliersproductsmodel',
            options={'ordering': ['id'], 'verbose_name': 'Supplier Product', 'verbose_name_plural': 'Supplier Products'},
        ),
        migrations.AlterField(
            model_name='suppliersproductsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
