# Generated by Django 5.2.5 on 2025-09-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_suppliersproductsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersproductsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='PromosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField()),
                ('start_promo_date', models.DateField()),
                ('end_promo_date', models.DateField()),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('confirm_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.suppliersproductsmodel')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['id'],
            },
        ),
    ]
