# Generated by Django 5.2.5 on 2025-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_suppliersproductsmodel_price_promosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
