# Generated by Django 5.2.5 on 2025-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_promosmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promosmodel',
            name='confirm_price',
        ),
        migrations.AlterField(
            model_name='suppliersproductsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
